   ! NOTE: This source file contains an example UserVSCont() user-specified
   !       routine for computing variable-speed controlled generator torque
   !       based on a table look-up of LSS speed and LSS torque provided in a
   !       spd_trq.dat input file.  It also contains an example UserGen, which
   !       calls UserVSCont.  These routines were written by Kirk Pierce (KP),
   !       formerly of NREL/NWTC, and now with GE Wind Energy.  Questions
   !       related to the use of these routines should be addressed to Kirk
   !       Pierce.

!=======================================================================
SUBROUTINE UserGen ( HSS_Spd, GBRatio, NumBl, ZTime, DT, GenEff, DelGenTrq, DirRoot, GenTrq, ElecPwr )


   ! This  example UserGen() is used do the same thing as SUBROUTINE
   !   UserVSCont(), so that setting VSContrl to 0 and GenModel o 3 does
   !   the same thing as setting VSContrl to 2.


USE                            Precision


IMPLICIT                       NONE


   ! Passed Variables:

INTEGER(4), INTENT(IN )     :: NumBl                                         ! Number of blades, (-).

REAL(ReKi), INTENT(IN )     :: DelGenTrq                                     ! Pertubation in generator torque used during FAST linearization (zero otherwise), N-m.
REAL(ReKi), INTENT(IN )     :: DT                                            ! Integration time step, sec.
REAL(ReKi), INTENT(OUT)     :: ElecPwr                                       ! Electrical power (account for losses), watts.
REAL(ReKi), INTENT(IN )     :: GBRatio                                       ! Gearbox ratio, (-).
REAL(ReKi), INTENT(IN )     :: GenEff                                        ! Generator efficiency, (-).
REAL(ReKi), INTENT(OUT)     :: GenTrq                                        ! Electrical generator torque, N-m.
REAL(ReKi), INTENT(IN )     :: HSS_Spd                                       ! HSS speed, rad/s.
REAL(ReKi), INTENT(IN )     :: ZTime                                         ! Current simulation time, sec.

CHARACTER(1024),INTENT(IN ) :: DirRoot                                       ! The name of the root file including the full path to the current working directory.  This may be useful if you want this routine to write a permanent record of what it does to be stored with the simulation results: the results should be stored in a file whose name (including path) is generated by appending any suitable extension to DirRoot.



CALL UserVSCont ( HSS_Spd, GBRatio, NumBl, ZTime, DT, GenEff, DelGenTrq, DirRoot, GenTrq, ElecPwr )   ! Let's have UserGen() do the same thing as SUBROUTINE UserVSCont().



RETURN
END SUBROUTINE UserGen
!=======================================================================

!=======================================================================
